name: Node.js CI

on:
  - push
  - pull_request

jobs:
  cover:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.2
          run_install: true
      - name: Run build
        run: pnpm run build
      - name: Run lint
        run: pnpm run lint
      - name: Run cover
        run: pnpm run cover
  report:
    needs: [cover]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.2
          run_install: true
      - name: Run build
        run: pnpm run build
      - name: Run cover
        run: pnpm run cover
      - name: Run report
        run: pnpm run report
      - uses: codecov/codecov-action@v2
        with:
          flags: unittests
          directory: ./coverage
          files: lcov.info
          verbose: true
  publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [report]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.2
          run_install: true
      - name: Run build
        run: pnpm run build
      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Publish
        run: pnpm publish -r --access public
