name: Test CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  cover:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install dependencies
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.1
          run_install: true
      - name: Run lint
        run: pnpm run lint
      - name: Run cover
        run: pnpm run cover
      - name: Run report
        run: pnpm run report
      - uses: codecov/codecov-action@v2
        with:
          flags: unittests
          directory: ./coverage
          files: lcov.info
          verbose: true
